# Dockerfile
FROM python:3.8

WORKDIR /app

# Install dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3.9 git && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN python3.9 -m pip install --no-cache-dir -r requirements.txt

# Copy code
COPY . .
RUN mv app/app_timgan.py app/app.py

# Environment variables
ENV PYTHONPATH=/app:/app/app
ENV HF_HOME=/app/huggingface_cache
ENV MODEL_TYPE=timegan

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]