# Dockerfile
FROM python:3.9

WORKDIR /app

# Install dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt
RUN pip install fastapi>=0.95.0 uvicorn>=0.21.0 python-multipart
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
# RUN pip uninstall -y nvidia_cublas_cu11
# Copy code
COPY . .
RUN mv /app/app_rtsgan /app/app
# RUN properties
# Environment variables
ENV PYTHONPATH=/app:/app/app
ENV HF_HOME=/app/huggingface_cache
ENV MODEL_TYPE=rtsgan

# CMD ["/bin/bash"]
CMD ["/usr/local/bin/uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]